// Build script for VKify16.
//
// Concatenates and minifies the themepack's modular JS (res/js/**) into a
// single IIFE bundle at res/js/dist/vk2020.bundle.js.
//
// core/vkify.js is NOT bundled: it loads non-deferred in @layout.latte so
// that synchronous consumers (core/settings-config.js and the inline
// vkifylang setup) see window.vkify immediately. All
// bundled modules are deferred and therefore execute after that script, so
// they can safely reference window.vkify at runtime.

import * as esbuild from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const jsRoot = path.join(__dirname, 'res', 'js');
const outFile = path.join(jsRoot, 'dist', 'vk2020.bundle.js');

// Load order, relative to res/js/.
const modules = [
    'utils/content-fetcher.js',

    'utils/loader-utils.js',
    'ui/textarea-autosize.js',
    'ui/message-box-overrides.js',
    'ui/choice-labels.js',

    'ui/sidebar-affix.js',
    'ui/custom-select.js',
    'ui/tab-slider.js',
    'ui/tooltips-simple.js',
    'ui/form-modal.js',
    'ui/notifications-popup.js',
    'ui/search-fasttips.js',

    'compat/player-stub.js',

    'ui/search.js',
    'ui/music-popup.js',
    'utils/modal-utils.js',
    'ui/media-modals.js',
    'ui/graffiti.js',
    'ui/action-menu.js',

    'features/attachment-picker.js',
    'features/post-count.js',
    'features/wall.js',
    'features/player.js',

    'features/status-editor.js',
    'features/pin-group.js',
    'features/profile.js',
    'features/likes.js',
    'features/paginator.js',
    'features/album-photos-loader.js',
    'features/audio-upload.js',
    'features/avatar-upload.js',
    "features/video-audio-coord.js",
    'features/video-delete.js',
];

for (const rel of modules) {
    const abs = path.join(jsRoot, rel);
    if (!fs.existsSync(abs)) {
        console.error(`[vk2020-build] Missing module: ${rel}`);
        process.exit(1);
    }
}

const entryContents = modules.map(rel => `import './${rel}';`).join('\n') + '\n';

const bundleOneLinerPlugin = {
    name: 'bundle-oneliner',
    setup(build) {
        build.onEnd(result => {
            if (result.outputFiles) {
                for (let file of result.outputFiles) {
                    if (file.path.endsWith('.js')) {
                        const collapsed = file.text.replace(/\r?\n\s*/g, ' ').trim() + '\n';
                        file.contents = Buffer.from(collapsed);
                    }
                    fs.mkdirSync(path.dirname(file.path), { recursive: true });
                    fs.writeFileSync(file.path, file.contents);
                }
            }
        });
    }
};

const buildOptions = {
    stdin: {
        contents: entryContents,
        resolveDir: jsRoot,
        sourcefile: '_entry.js',
        loader: 'js',
    },
    bundle: true,
    format: 'iife',
    target: 'es2017',
    minifyWhitespace: true,
    minifySyntax: true,
    minifyIdentifiers: false,
    keepNames: true,
    sourcemap: true,
    legalComments: 'linked',
    outfile: outFile,
    logLevel: 'info',
    metafile: true,
    write: false,
    banner: {
        js: '/* VKify16 themepack bundle. Generated by build.mjs. Do not edit by hand. */',
    },
    plugins: [bundleOneLinerPlugin],
};

const watch = process.argv.includes('--watch');

if (watch) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log('[vk2020-build] Watching for changes...');
} else {
    const result = await esbuild.build(buildOptions);
    const file = result.outputFiles.find(f => f.path === outFile);
    if (file) {
        console.log(`[vk2020-build] Wrote ${path.relative(__dirname, outFile)} (${(file.contents.length / 1024).toFixed(1)} KB)`);
    }
}